### PR TITLE
use the -RH (report hashrate) option of ethminer

### PR DESCRIPTION
**Pull request by bartocc**
I use it and this could be a good default

### CODE REVIEW

**Comment by Cyclenerd** [comment]
Help says:

> Report current hashrate to pool (please only enable on pools supporting this)

Does that make problems when a pool can not? I can not test that.

**Comment by bartocc** [comment]
I don't know actually. I've only used this on ethermine.org

**Comment by bartocc** [comment]
Mayby this is not a good default if not all pools support it…

**Comment by Cyclenerd** [comment]
I close the pull.

**Pull request closed without merging**
