### PR TITLE
Update nvidia-overclock.sh

### PR DESCRIPTION
**Pull request by metatsmith**
Automagically detect the number of cards rather than hard-code 6.  Fixed spelling mistake.

### CODE REVIEW

**Comment by metatsmith** [comment]
Never would have thought my first github interaction would be changing a mining script.  But hey, I feel like I contributed or something.

**Comment by Cyclenerd** [comment]
Hi,

thanks for the pull. Please look here:
https://github.com/Cyclenerd/ethereum_nvidia_miner/issues/39

`lspci` is not right for it. Better would be `nvidia-smi --list-gpus`. I had it already: More card in `lspci` as drivers loaded.

And here are a few hints:

* Use `$(..)` instead of legacy `'..'`.
* Consider using `grep -c` instead of `grep|wc -l`.
* `expr` is antiquated. Consider rewriting this using` $((..))`, `${}` or `[[ ]]`.
* Double quote to prevent globbing and word splitting.
* Use http://www.shellcheck.net/ :-)

**Comment by cudarender** [comment]
Hello, 
How i can install this script on Clean install Ubuntu 16.04 64 bit, (Not USB boot) install this on Harddisk install OS Ubuntu

Thanks you

**Comment by ykhuat** [comment]
Hai, tq for good work here.. I have a issue it was running out of space for "/", How to free up the space?

**Comment by Cyclenerd** [comment]
Sad, that even PR  are abused for stupid questions. Learn to use Google!

@brainquan @ykhuat : http://gph.is/2rQSwV2

I therefore also close this PR.

@metatsmith : When you're done, just make a new PR.

**Pull request closed without merging**
