### PR TITLE
Update nvidia-overclock.sh

### PR DESCRIPTION
**Pull request by invidtiv**
Hello, I propose this change, this will eliminate the need to edit the file to place the correct number of gpu .

### CODE REVIEW

**Comment by Roaders** [comment]
I made the same change locally to support 12 cards.

**Comment by Cyclenerd** [comment]
Hi,

Thanks for this pull request.

Please fix the reported errors from codeclimate:

**Problematic code:**
`echo $(($n+1))`

**Correct code:**
`echo $((n+1))`

Please start variables with `MY_`.

Persistence mode is set in `miner.sh`.

Best regards
Nils

**Comment by AndreaLanfranchi** [comment]
My two cents about it.
I consider this change creates unneded calls to like 

`if nvidia-smi -i $MY_DEVICE`

which is pleonastic (we have already collected the existing cards).

Thus my correction to script is :

```
nvidia-smi --format=csv,noheader --query-gpu=index | while read device; do
   [...]
    nvidia-settings -a "[gpu:$device]/GPUFanControlState=1"
done;
```

No need to 

1. set extra variable like NUMGPU and rebase it to zero
2. do an extra check for existence of GPU

**Comment by Cyclenerd** [comment]
Very good idea. Makes sense! @AndreaLanfranchi 

Have changed that quickly (https://github.com/Cyclenerd/ethereum_nvidia_miner/commit/541f7b1a87d07a41c713b8fb66a53d382db515df) and will close this pull.

**Pull request closed without merging**
