### PR TITLE
Better Output on GPU monitor page

### PR DESCRIPTION
**Pull request by AndreaLanfranchi**
Added some information and formatted in columns

### CODE REVIEW

**Comment by Cyclenerd** [comment]
Thanks for the pull. 

The output is a little too long (>120 columns)

I would be for:

```
prospector@mine2:~ $ nvidia-smi --format=csv --query-gpu=index,name,power.draw,temperature.gpu,fan.speed,clocks.gr,clocks.mem | column -s, -t
index   name               power.draw [W]   temperature.gpu   fan.speed [%]   clocks.current.graphics [MHz]   clocks.current.memory [MHz]
0       GeForce GTX 1080   131.17 W         38                70 %            1708 MHz                        4873 MHz
1       GeForce GTX 1080   131.13 W         35                70 %            1721 MHz                        4873 MHz
```

The other details you get in the `smi` tab.

**Comment by AndreaLanfranchi** [comment]
I would keep at least the timestamp as 

1. sometimes you stare at the screen and nothing changes (changed date in the upper right corner is away from sight). It happened to me that the driver was dead but i thought it was running.
2. it gives useful information about how responsive driver is (milliseconds difference among different rows)

**Comment by AndreaLanfranchi** [comment]
Also to be noted that Power Drawn on Gtx 1050 is no longer working on recent drivers.

**Comment by spotcatbug** [comment]
I just implemented this awesome fix on my rigs (never new about column).

You can fix the "it's too wide" problem by replacing the column headers
with shorter strings. Like "clocks.current.graphics [MHz]" could simply be
"Core Clock." Don't even need the "[MHz]" because the units are on the
numbers in the column.

-Sherman.

**Comment by Cyclenerd** [comment]
Yes, this could work:

```
(echo "Time, ID, Name, Power, Temp, Fan, Gpu, Mem"; nvidia-smi --format=csv,noheader --query-gpu=timestamp,index,name,power.draw,temperature.gpu,fan.speed,clocks.gr,clocks.mem ) | column -s, -t

Time                      ID   Name               Power      Temp   Fan    Gpu        Mem
2018/03/08 19:23:17.584   0    GeForce GTX 1080   125.29 W   57     70 %   1733 MHz   4873 MHz
2018/03/08 19:23:17.611   1    GeForce GTX 1080   129.27 W   40     70 %   1771 MHz   4873 MHz
2018/03/08 19:23:17.632   2    GeForce GTX 1080   128.66 W   62     70 %   1683 MHz   4873 MHz
```

**Comment by AndreaLanfranchi** [comment]
Output is now 

```
Time                      Id   Name                   St   P.Lim     P.Draw    Temp   Fan    Gpu     Mem
2018/03/08 20:10:24.025   0    GeForce GTX 1060 6GB   P2   85.00 W   84.33 W   52     80 %   1430    4788
2018/03/08 20:10:24.031   1    GeForce GTX 1060 6GB   P2   85.00 W   84.80 W   56     80 %   1430    4788
2018/03/08 20:10:24.049   2    GeForce GTX 1060 6GB   P2   85.00 W   84.83 W   56     80 %   1366    4788
2018/03/08 20:10:24.057   3    GeForce GTX 1060 6GB   P2   85.00 W   84.62 W   56     80 %   1442    4788
2018/03/08 20:10:24.062   4    GeForce GTX 1060 6GB   P2   85.00 W   85.14 W   55     80 %   1417    4788
2018/03/08 20:10:24.071   5    GeForce GTX 1060 6GB   P2   85.00 W   83.83 W   51     80 %   1404    4788
```

**Comment by Cyclenerd** [comment]
great!

**Pull request merged**
