### PR TITLE
Further Improvement in GPU Monitor screen - part 2

### PR DESCRIPTION
**Pull request by AndreaLanfranchi**
Gained some more chars by
removing date part in timestamp (we should know which date we're on)
removing " W" unit of measure
removing "Geforce" label on GPUs

### CODE REVIEW

**Comment by AndreaLanfranchi** [comment]
New more compact output

```
Time           Id   Name           St   P.Lim   P.Draw   Temp   Fan    Gpu     Mem
20:41:46.504   0    GTX 1060 6GB   P2   85.00   84.42    52     80 %   1430    4788
20:41:46.518   1    GTX 1060 6GB   P2   85.00   84.66    55     80 %   1430    4788
20:41:46.523   2    GTX 1060 6GB   P2   85.00   84.54    56     80 %   1366    4788
20:41:46.529   3    GTX 1060 6GB   P2   85.00   83.76    56     80 %   1430    4788
20:41:46.534   4    GTX 1060 6GB   P2   85.00   85.14    54     80 %   1417    4788
20:41:46.540   5    GTX 1060 6GB   P2   85.00   83.74    51     80 %   1404    4788

```

**Comment by Cyclenerd** [comment]
In the pull is only delete. 

Maybe `nounits` better: `--format=csv,noheader,nounits`

**Comment by AndreaLanfranchi** [comment]
I meant to keep "%" in fan percent

**Comment by Cyclenerd** [comment]
Unity should be as clear as the others.

**Comment by AndreaLanfranchi** [comment]
```
Time           Id   Name           St   P.Lim   P.Draw   Temp   Fan   Gpu    Mem
20:52:50.604   0    GTX 1060 6GB   P2   85.00   84.52    52     80    1430   4788
20:52:50.608   1    GTX 1060 6GB   P2   85.00   84.59    55     80    1430   4788
20:52:50.614   2    GTX 1060 6GB   P2   85.00   85.68    56     80    1379   4788
20:52:50.623   3    GTX 1060 6GB   P2   85.00   83.76    56     80    1430   4788
20:52:50.628   4    GTX 1060 6GB   P2   85.00   85.14    54     80    1417   4788
20:52:50.645   5    GTX 1060 6GB   P2   85.00   85.63    51     80    1442   4788


```

**Comment by Cyclenerd** [comment]
very good!

**Pull request merged**
